version: '3'
services:

    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always
        ports:
            - "23760:80"
        depends_on:
            - web

    web:
        container_name: web
        build: ./web
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./web/app:/app
